### ISSUE TITLE
With angular 6 throw the rxjs error Observable.fromEvent is not a function

### ISSUE THREAD

**Issue by yduartep** [hardy12994/ng5-auto-complete#5]
I'm trying to use this component with angular 6 but I receive on runtime the following error:

rxjs__WEBPACK_IMPORTED_MODULE_1__.Observable.fromEvent is not a function

I have installed also the library rxjs-compat to avoid retro compatibility with the previous versions of rxjs but still not working.

**Comment by ghost** [comment]
With angular 6. The import:
import { Observable, fromEvent } from 'rxjs';

The fromEvent:
keys$:Observable<any> = fromEvent( document, 'keyup')

**Comment by hardeep-bit** [comment]
Hi @yduartep @roblassche this module is only for NG5 . NOT for above angular Version. It *may* work in above version to 5.0.0 of angular but their are also chances that may not work with NG6. Let you know when this module is updated. Thank you
